//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WisModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasProfile
    {
        public string WSysCode { get; set; }
        public string WSysCreateCode { get; set; }
        public System.DateTime WSysCreateUtc { get; set; }
        public string WSysUpdateCode { get; set; }
        public System.DateTime WSysUpdateUtc { get; set; }
        public byte WSysStatusFlg { get; set; }
        public byte WSysIsDelete { get; set; }
        public string WFullName { get; set; }
        public string WEmail { get; set; }
        public string WBirthday { get; set; }
        public Nullable<byte> WSex { get; set; }
    }
}
