//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WisModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WisEntities : DbContext
    {
        public WisEntities()
            : base("name=WisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MasCity> MasCities { get; set; }
        public virtual DbSet<MasCountry> MasCountries { get; set; }
        public virtual DbSet<MasDistrict> MasDistricts { get; set; }
        public virtual DbSet<MasManager> MasManagers { get; set; }
        public virtual DbSet<MasProfile> MasProfiles { get; set; }
        public virtual DbSet<SearchAddress> SearchAddresses { get; set; }
        public virtual DbSet<SearchCategory> SearchCategories { get; set; }
        public virtual DbSet<SearchRate> SearchRates { get; set; }
        public virtual DbSet<TempAddress> TempAddresses { get; set; }
    }
}
